name: 'Delete Neon Project'
description: 'Delete Neon Project using API'

inputs:
  access_token:
    description: 'Lakebase API access token'
    required: true
  org_id:
    description: 'Organization ID, required'
    required: true
  api_host:
    description: 'Lakebase API host, e.g. dbc-55e65913-66de.dev.databricks.com/ajax-api/2.0/lakebase-console'
    required: true
  project_id:
    description: 'ID of the Project to delete'
    required: true

runs:
  using: "composite"
  steps:
    - name: Delete Lakebase Project
      # Do not try to delete a project if .github/actions/neon-project-create failed before
      if: ${{ inputs.project_id != '' }}
      shell: bash -euxo pipefail {0}
      run: |
        curl \
          "https://${API_HOST}/api/v2/projects/${PROJECT_ID}" \
          --fail \
          --request DELETE \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer ${ACCESS_TOKEN}" 

        echo "Project ${PROJECT_ID} has been deleted"
      env:
        API_HOST: ${{ inputs.api_host }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
        ORG_ID: ${{ inputs.org_id }}
        PROJECT_ID: ${{ inputs.project_id }}
